name: Generate artifact & update documentation

on:
  push:
    branches:
      - master
      - main
      - develop
    paths:
      - models/**

  workflow_dispatch:
    inputs:
      version:
        description: 'Artifact version'
        required: false
        type: string

defaults:
  run:
    working-directory: models/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          mirrors: >
            [
              {
                "id": "libs-snapshot",
                "name": "libs-snapshot",
                "mirrorOf": "*,!libs-snapshot,!libs-release,!libs-snapshot-local,!libs-release-local,!plugins-snapshot-local,!plugins-release-local,!ext-snapshot-local,!ext-release-local",
                "url": "https://dbartifactory.jfrog.io/dbartifactory/all"
              }
            ]
          repositories: >
            [
              { 
                "id": "central",
                "name": "libs-release",
                "url": "https://dbartifactory.jfrog.io/dbartifactory/libs-release",
                "snapshots": {
                  "enabled": "false"
                }
              },
              { 
                "id": "snapshots", 
                "name": "libs-snapshot",
                "url": "https://dbartifactory.jfrog.io/dbartifactory/libs-snapshot",
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              } 
            ]
          plugin_repositories: >
            [
              {
                "id": "central",
                "name": "plugins-release",
                "url": "https://dbartifactory.jfrog.io/dbartifactory/plugins-release",
                "snapshots": {
                  "enabled": "false"
                }
              },
              {
                "id": "snapshots",
                "name": "plugins-snapshot",
                "url": "https://dbartifactory.jfrog.io/dbartifactory/plugins-snapshot",
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              }
            ]
          profiles: >
            [
              {
                "id": "artifactory"
              }
            ]
          active_profiles: >
            [
              "artifactory"
            ]
      - name: Extract yaml version
        id: version-extractor
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: models/spec.yaml
          revision: info.version

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build with Maven
        run: revision="" && if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then revision=${{ steps.version-extractor.outputs.revision }}; elif [ ${{ inputs.version }} ]; then revision=${{ inputs.version }}-${{ steps.vars.outputs.sha_short }}; else revision=${{ steps.version-extractor.outputs.revision }}-${{ steps.vars.outputs.sha_short }}; fi && mvn clean install -Drevision="$revision"

      - name: Update documentation
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event_name != "workflow_dispatch"
        with:
          file_pattern: models/docs/.
          push_options: '--force-with-lease'
